title: Default Page

tabs:
  content:
    label: Page Content
    fields:
      pageTitle:
        label: Page Title
        type: text

      text:
        label: Text
        type: textarea
        size: large

  seo: seo/page
