title: Default Page
preset: page
fields:
  pageTitle:
    label: Page Title
    type: text
  description:
    label: Meta Description
    type: text
  text:
    label: Text
    type: textarea
    size: large
