<?php
  // ref https://github.com/brocessing/kirby-webpack

  // check for header set in browsersync (tools/srcServer)
  function isWebpack() {
    return !!(
      isset($_SERVER['HTTP_X_FORWARDED_FOR'])
        && $_SERVER['HTTP_X_FORWARDED_FOR'] == 'webpack'
    );
  }

  // Use instead of css() for all your css files generated by webpack.
  // This will enable the livereload feature when your are in development
  function prodCSS ($href, $media = null) {
    return isWebpack()
      ? ''
      : css($href, $media);
  }

  function liveJs($path, $file) {
    return isWebpack()
      ? js($file)
      : js($path . '/' . $file);
  }