require('normalize.css');
// import 'remixicon/fonts/remixicon.css';
require('./scss/site.scss');
require('./fixedNav');
require('./scrollTop');
require('./images/logo-sprites.png');
require('./images/logo.png');
require('./images/logo-dark.png');
require('./images/frog-sprites.png');
require('./images/frog.png');
require('./images/frog-dark.png');
